//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    [System.ComponentModel.Description("X.OA.Model.OAEntities")]
    public partial class KeywordRank
    {
        public int Id { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> SearchCount { get; set; }
    }
}
