//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.OA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAEntities : DbContext
    {
        public OAEntities()
            : base("name=OAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<ActionInfo> ActionInfoes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FileInfo> FileInfoes { get; set; }
        public virtual DbSet<OrderInfo> OrderInfoes { get; set; }
        public virtual DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual DbSet<RoleInfo> RoleInfoes { get; set; }
        public virtual DbSet<WF_Instance> WF_Instance { get; set; }
        public virtual DbSet<WF_StepInfo> WF_StepInfo { get; set; }
        public virtual DbSet<WF_Temp> WF_Temp { get; set; }
        public virtual DbSet<KeywordRank> KeywordRanks { get; set; }
        public virtual DbSet<SearchDetail> SearchDetails { get; set; }
    }
}
