//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerInfo()
        {
            this.ImageInfoes = new HashSet<ImageInfo>();
        }
    
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string ServerUrl { get; set; }
        public string PicPath { get; set; }
        public int MaxAmount { get; set; }
        public int CurrentAmount { get; set; }
        public bool IsAlive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageInfo> ImageInfoes { get; set; }
    }
}
