//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("OAModel2", "FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(X.OA.Model.ActionInfo), "R_UserInfo_ActionInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.R_UserInfo_ActionInfo), true)]
[assembly: EdmRelationshipAttribute("OAModel2", "FK_UserInfoR_UserInfo_ActionInfo", "UserInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(X.OA.Model.UserInfo), "R_UserInfo_ActionInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.R_UserInfo_ActionInfo), true)]
[assembly: EdmRelationshipAttribute("OAModel2", "RoleInfoActionInfo", "ActionInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.ActionInfo), "RoleInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.RoleInfo))]
[assembly: EdmRelationshipAttribute("OAModel2", "UserInfoRoleInfo", "RoleInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.RoleInfo), "UserInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(X.OA.Model.UserInfo))]

#endregion

namespace X.OA.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class OAEntities2 : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“OAEntities2”部分中的连接字符串初始化新 OAEntities2 对象。
        /// </summary>
        public OAEntities2() : base("name=OAEntities2", "OAEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAEntities2 对象。
        /// </summary>
        public OAEntities2(string connectionString) : base(connectionString, "OAEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAEntities2 对象。
        /// </summary>
        public OAEntities2(EntityConnection connection) : base(connection, "OAEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ActionInfo> ActionInfoes
        {
            get
            {
                if ((_ActionInfoes == null))
                {
                    _ActionInfoes = base.CreateObjectSet<ActionInfo>("ActionInfoes");
                }
                return _ActionInfoes;
            }
        }
        private ObjectSet<ActionInfo> _ActionInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo
        {
            get
            {
                if ((_R_UserInfo_ActionInfo == null))
                {
                    _R_UserInfo_ActionInfo = base.CreateObjectSet<R_UserInfo_ActionInfo>("R_UserInfo_ActionInfo");
                }
                return _R_UserInfo_ActionInfo;
            }
        }
        private ObjectSet<R_UserInfo_ActionInfo> _R_UserInfo_ActionInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RoleInfo> RoleInfoes
        {
            get
            {
                if ((_RoleInfoes == null))
                {
                    _RoleInfoes = base.CreateObjectSet<RoleInfo>("RoleInfoes");
                }
                return _RoleInfoes;
            }
        }
        private ObjectSet<RoleInfo> _RoleInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserInfo> UserInfoes
        {
            get
            {
                if ((_UserInfoes == null))
                {
                    _UserInfoes = base.CreateObjectSet<UserInfo>("UserInfoes");
                }
                return _UserInfoes;
            }
        }
        private ObjectSet<UserInfo> _UserInfoes;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ActionInfoes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToActionInfoes(ActionInfo actionInfo)
        {
            base.AddObject("ActionInfoes", actionInfo);
        }
    
        /// <summary>
        /// 用于向 R_UserInfo_ActionInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToR_UserInfo_ActionInfo(R_UserInfo_ActionInfo r_UserInfo_ActionInfo)
        {
            base.AddObject("R_UserInfo_ActionInfo", r_UserInfo_ActionInfo);
        }
    
        /// <summary>
        /// 用于向 RoleInfoes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRoleInfoes(RoleInfo roleInfo)
        {
            base.AddObject("RoleInfoes", roleInfo);
        }
    
        /// <summary>
        /// 用于向 UserInfoes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserInfoes(UserInfo userInfo)
        {
            base.AddObject("UserInfoes", userInfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel2", Name="ActionInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActionInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ActionInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="subTime">SubTime 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        /// <param name="modifiedOn">ModifiedOn 属性的初始值。</param>
        /// <param name="url">Url 属性的初始值。</param>
        /// <param name="httpMethod">HttpMethod 属性的初始值。</param>
        /// <param name="actionInfoName">ActionInfoName 属性的初始值。</param>
        /// <param name="actionTypeEnum">ActionTypeEnum 属性的初始值。</param>
        /// <param name="iconWidth">IconWidth 属性的初始值。</param>
        /// <param name="iconHeight">IconHeight 属性的初始值。</param>
        public static ActionInfo CreateActionInfo(global::System.Int32 id, global::System.DateTime subTime, global::System.Int16 delFlag, global::System.String modifiedOn, global::System.String url, global::System.String httpMethod, global::System.String actionInfoName, global::System.Int16 actionTypeEnum, global::System.Int32 iconWidth, global::System.Int32 iconHeight)
        {
            ActionInfo actionInfo = new ActionInfo();
            actionInfo.ID = id;
            actionInfo.SubTime = subTime;
            actionInfo.DelFlag = delFlag;
            actionInfo.ModifiedOn = modifiedOn;
            actionInfo.Url = url;
            actionInfo.HttpMethod = httpMethod;
            actionInfo.ActionInfoName = actionInfoName;
            actionInfo.ActionTypeEnum = actionTypeEnum;
            actionInfo.IconWidth = iconWidth;
            actionInfo.IconHeight = iconHeight;
            return actionInfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubTime
        {
            get
            {
                return _SubTime;
            }
            set
            {
                OnSubTimeChanging(value);
                ReportPropertyChanging("SubTime");
                _SubTime = StructuralObject.SetValidValue(value, "SubTime");
                ReportPropertyChanged("SubTime");
                OnSubTimeChanged();
            }
        }
        private global::System.DateTime _SubTime;
        partial void OnSubTimeChanging(global::System.DateTime value);
        partial void OnSubTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value, "DelFlag");
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int16 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int16 value);
        partial void OnDelFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, false, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.String _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.String value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true, "Remark");
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HttpMethod
        {
            get
            {
                return _HttpMethod;
            }
            set
            {
                OnHttpMethodChanging(value);
                ReportPropertyChanging("HttpMethod");
                _HttpMethod = StructuralObject.SetValidValue(value, false, "HttpMethod");
                ReportPropertyChanged("HttpMethod");
                OnHttpMethodChanged();
            }
        }
        private global::System.String _HttpMethod;
        partial void OnHttpMethodChanging(global::System.String value);
        partial void OnHttpMethodChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionMethodName
        {
            get
            {
                return _ActionMethodName;
            }
            set
            {
                OnActionMethodNameChanging(value);
                ReportPropertyChanging("ActionMethodName");
                _ActionMethodName = StructuralObject.SetValidValue(value, true, "ActionMethodName");
                ReportPropertyChanged("ActionMethodName");
                OnActionMethodNameChanged();
            }
        }
        private global::System.String _ActionMethodName;
        partial void OnActionMethodNameChanging(global::System.String value);
        partial void OnActionMethodNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ControllerName
        {
            get
            {
                return _ControllerName;
            }
            set
            {
                OnControllerNameChanging(value);
                ReportPropertyChanging("ControllerName");
                _ControllerName = StructuralObject.SetValidValue(value, true, "ControllerName");
                ReportPropertyChanged("ControllerName");
                OnControllerNameChanged();
            }
        }
        private global::System.String _ControllerName;
        partial void OnControllerNameChanging(global::System.String value);
        partial void OnControllerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActionInfoName
        {
            get
            {
                return _ActionInfoName;
            }
            set
            {
                OnActionInfoNameChanging(value);
                ReportPropertyChanging("ActionInfoName");
                _ActionInfoName = StructuralObject.SetValidValue(value, false, "ActionInfoName");
                ReportPropertyChanged("ActionInfoName");
                OnActionInfoNameChanged();
            }
        }
        private global::System.String _ActionInfoName;
        partial void OnActionInfoNameChanging(global::System.String value);
        partial void OnActionInfoNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, true, "Sort");
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ActionTypeEnum
        {
            get
            {
                return _ActionTypeEnum;
            }
            set
            {
                OnActionTypeEnumChanging(value);
                ReportPropertyChanging("ActionTypeEnum");
                _ActionTypeEnum = StructuralObject.SetValidValue(value, "ActionTypeEnum");
                ReportPropertyChanged("ActionTypeEnum");
                OnActionTypeEnumChanged();
            }
        }
        private global::System.Int16 _ActionTypeEnum;
        partial void OnActionTypeEnumChanging(global::System.Int16 value);
        partial void OnActionTypeEnumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MenuIcon
        {
            get
            {
                return _MenuIcon;
            }
            set
            {
                OnMenuIconChanging(value);
                ReportPropertyChanging("MenuIcon");
                _MenuIcon = StructuralObject.SetValidValue(value, true, "MenuIcon");
                ReportPropertyChanged("MenuIcon");
                OnMenuIconChanged();
            }
        }
        private global::System.String _MenuIcon;
        partial void OnMenuIconChanging(global::System.String value);
        partial void OnMenuIconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IconWidth
        {
            get
            {
                return _IconWidth;
            }
            set
            {
                OnIconWidthChanging(value);
                ReportPropertyChanging("IconWidth");
                _IconWidth = StructuralObject.SetValidValue(value, "IconWidth");
                ReportPropertyChanged("IconWidth");
                OnIconWidthChanged();
            }
        }
        private global::System.Int32 _IconWidth;
        partial void OnIconWidthChanging(global::System.Int32 value);
        partial void OnIconWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IconHeight
        {
            get
            {
                return _IconHeight;
            }
            set
            {
                OnIconHeightChanging(value);
                ReportPropertyChanging("IconHeight");
                _IconHeight = StructuralObject.SetValidValue(value, "IconHeight");
                ReportPropertyChanged("IconHeight");
                OnIconHeightChanged();
            }
        }
        private global::System.Int32 _IconHeight;
        partial void OnIconHeightChanging(global::System.Int32 value);
        partial void OnIconHeightChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "FK_ActionInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo")]
        public EntityCollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<R_UserInfo_ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<R_UserInfo_ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "RoleInfoActionInfo", "RoleInfo")]
        public EntityCollection<RoleInfo> RoleInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoleInfo>("OAModel2.RoleInfoActionInfo", "RoleInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoleInfo>("OAModel2.RoleInfoActionInfo", "RoleInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel2", Name="R_UserInfo_ActionInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class R_UserInfo_ActionInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 R_UserInfo_ActionInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userInfoID">UserInfoID 属性的初始值。</param>
        /// <param name="actionInfoID">ActionInfoID 属性的初始值。</param>
        /// <param name="isPass">IsPass 属性的初始值。</param>
        public static R_UserInfo_ActionInfo CreateR_UserInfo_ActionInfo(global::System.Int32 id, global::System.Int32 userInfoID, global::System.Int32 actionInfoID, global::System.Boolean isPass)
        {
            R_UserInfo_ActionInfo r_UserInfo_ActionInfo = new R_UserInfo_ActionInfo();
            r_UserInfo_ActionInfo.ID = id;
            r_UserInfo_ActionInfo.UserInfoID = userInfoID;
            r_UserInfo_ActionInfo.ActionInfoID = actionInfoID;
            r_UserInfo_ActionInfo.IsPass = isPass;
            return r_UserInfo_ActionInfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserInfoID
        {
            get
            {
                return _UserInfoID;
            }
            set
            {
                OnUserInfoIDChanging(value);
                ReportPropertyChanging("UserInfoID");
                _UserInfoID = StructuralObject.SetValidValue(value, "UserInfoID");
                ReportPropertyChanged("UserInfoID");
                OnUserInfoIDChanged();
            }
        }
        private global::System.Int32 _UserInfoID;
        partial void OnUserInfoIDChanging(global::System.Int32 value);
        partial void OnUserInfoIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionInfoID
        {
            get
            {
                return _ActionInfoID;
            }
            set
            {
                OnActionInfoIDChanging(value);
                ReportPropertyChanging("ActionInfoID");
                _ActionInfoID = StructuralObject.SetValidValue(value, "ActionInfoID");
                ReportPropertyChanged("ActionInfoID");
                OnActionInfoIDChanged();
            }
        }
        private global::System.Int32 _ActionInfoID;
        partial void OnActionInfoIDChanging(global::System.Int32 value);
        partial void OnActionInfoIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPass
        {
            get
            {
                return _IsPass;
            }
            set
            {
                OnIsPassChanging(value);
                ReportPropertyChanging("IsPass");
                _IsPass = StructuralObject.SetValidValue(value, "IsPass");
                ReportPropertyChanged("IsPass");
                OnIsPassChanged();
            }
        }
        private global::System.Boolean _IsPass;
        partial void OnIsPassChanging(global::System.Boolean value);
        partial void OnIsPassChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo")]
        public ActionInfo ActionInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ActionInfo> ActionInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ActionInfo>("OAModel2.FK_ActionInfoR_UserInfo_ActionInfo", "ActionInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "FK_UserInfoR_UserInfo_ActionInfo", "UserInfo")]
        public UserInfo UserInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "UserInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "UserInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserInfo> UserInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "UserInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "UserInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel2", Name="RoleInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoleInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RoleInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="roleName">RoleName 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        /// <param name="subTime">SubTime 属性的初始值。</param>
        /// <param name="modifiedOn">ModifiedOn 属性的初始值。</param>
        public static RoleInfo CreateRoleInfo(global::System.Int32 id, global::System.String roleName, global::System.Int16 delFlag, global::System.DateTime subTime, global::System.String modifiedOn)
        {
            RoleInfo roleInfo = new RoleInfo();
            roleInfo.ID = id;
            roleInfo.RoleName = roleName;
            roleInfo.DelFlag = delFlag;
            roleInfo.SubTime = subTime;
            roleInfo.ModifiedOn = modifiedOn;
            return roleInfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false, "RoleName");
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value, "DelFlag");
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int16 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int16 value);
        partial void OnDelFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubTime
        {
            get
            {
                return _SubTime;
            }
            set
            {
                OnSubTimeChanging(value);
                ReportPropertyChanging("SubTime");
                _SubTime = StructuralObject.SetValidValue(value, "SubTime");
                ReportPropertyChanged("SubTime");
                OnSubTimeChanged();
            }
        }
        private global::System.DateTime _SubTime;
        partial void OnSubTimeChanging(global::System.DateTime value);
        partial void OnSubTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true, "Remark");
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, false, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.String _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.String value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, true, "Sort");
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "RoleInfoActionInfo", "ActionInfo")]
        public EntityCollection<ActionInfo> ActionInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ActionInfo>("OAModel2.RoleInfoActionInfo", "ActionInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ActionInfo>("OAModel2.RoleInfoActionInfo", "ActionInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "UserInfoRoleInfo", "UserInfo")]
        public EntityCollection<UserInfo> UserInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserInfo>("OAModel2.UserInfoRoleInfo", "UserInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserInfo>("OAModel2.UserInfoRoleInfo", "UserInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel2", Name="UserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="uPwd">UPwd 属性的初始值。</param>
        /// <param name="subTime">SubTime 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        /// <param name="modifiedOn">ModifiedOn 属性的初始值。</param>
        public static UserInfo CreateUserInfo(global::System.Int32 id, global::System.String uPwd, global::System.DateTime subTime, global::System.Int16 delFlag, global::System.DateTime modifiedOn)
        {
            UserInfo userInfo = new UserInfo();
            userInfo.ID = id;
            userInfo.UPwd = uPwd;
            userInfo.SubTime = subTime;
            userInfo.DelFlag = delFlag;
            userInfo.ModifiedOn = modifiedOn;
            return userInfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UName
        {
            get
            {
                return _UName;
            }
            set
            {
                OnUNameChanging(value);
                ReportPropertyChanging("UName");
                _UName = StructuralObject.SetValidValue(value, true, "UName");
                ReportPropertyChanged("UName");
                OnUNameChanged();
            }
        }
        private global::System.String _UName;
        partial void OnUNameChanging(global::System.String value);
        partial void OnUNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UPwd
        {
            get
            {
                return _UPwd;
            }
            set
            {
                OnUPwdChanging(value);
                ReportPropertyChanging("UPwd");
                _UPwd = StructuralObject.SetValidValue(value, false, "UPwd");
                ReportPropertyChanged("UPwd");
                OnUPwdChanged();
            }
        }
        private global::System.String _UPwd;
        partial void OnUPwdChanging(global::System.String value);
        partial void OnUPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubTime
        {
            get
            {
                return _SubTime;
            }
            set
            {
                OnSubTimeChanging(value);
                ReportPropertyChanging("SubTime");
                _SubTime = StructuralObject.SetValidValue(value, "SubTime");
                ReportPropertyChanged("SubTime");
                OnSubTimeChanged();
            }
        }
        private global::System.DateTime _SubTime;
        partial void OnSubTimeChanging(global::System.DateTime value);
        partial void OnSubTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value, "DelFlag");
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int16 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int16 value);
        partial void OnDelFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.DateTime _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.DateTime value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true, "Remark");
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, true, "Sort");
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "FK_UserInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo")]
        public EntityCollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<R_UserInfo_ActionInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<R_UserInfo_ActionInfo>("OAModel2.FK_UserInfoR_UserInfo_ActionInfo", "R_UserInfo_ActionInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAModel2", "UserInfoRoleInfo", "RoleInfo")]
        public EntityCollection<RoleInfo> RoleInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoleInfo>("OAModel2.UserInfoRoleInfo", "RoleInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoleInfo>("OAModel2.UserInfoRoleInfo", "RoleInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
